// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olwjvtzcegyljcazyslg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sd2p2dHpjZWd5bGpjYXp5c2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwMzE0NzksImV4cCI6MjA1MTYwNzQ3OX0.Gqe2FSeyDWqU9j7RtSB_GextebQLgklVINBW32LzhgE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);